# Example location snippet
location / {
    SecRulesEnabled;
    DeniedUrl /RequestDenied;
    include checkrules.conf;
    include libinjection.conf;
    include request-905-common-exceptions.rules;
    include request-913-scanner-detection.rules;
    include request-920-protocol-enforcement.rules;
    include request-921-protocol-attack.rules;
    include request-922-multipart-attack.rules;
    include request-930-application-attack-lfi.rules;
    include request-931-application-attack-rfi.rules;
    include request-932-application-attack-rce.rules;
    include request-933-application-attack-php.rules;
    include request-934-application-attack-generic.rules;
    include request-941-application-attack-xss.rules;
    include request-942-application-attack-sqli.rules;
    include request-943-application-attack-session-fixation.rules;
    include request-944-application-attack-java.rules;
    include response-950-data-leakages.rules;
    include response-951-data-leakages-sql.rules;
    include response-952-data-leakages-java.rules;
    include response-953-data-leakages-php.rules;
    include response-954-data-leakages-iis.rules;
    include response-955-web-shells.rules;
    include response-956-data-leakages-ruby.rules;
}
